name: Sign Container Image
description: Sign container image using cosign with keyless signing

inputs:
  image-digest:
    description: 'Image digest to sign'
    required: true
  image-tags:
    description: 'Image tags (space or newline separated)'
    required: true

runs:
  using: composite
  steps:
    - name: Install cosign
      uses: sigstore/cosign-installer@v3

    - name: Sign image with cosign
      shell: bash
      env:
        DIGEST: ${{ inputs.image-digest }}
        TAGS: ${{ inputs.image-tags }}
      run: |
        images=""
        for tag in ${TAGS}; do
          images+="${tag}@${DIGEST} "
        done
        echo "Signing images: ${images}"
        cosign sign --yes ${images}
