name: Docker Build and Push
description: Build, tag, and push Docker image with metadata, SBOM, and provenance

inputs:
  context:
    description: 'Build context directory'
    required: true
  dockerfile:
    description: 'Path to Dockerfile'
    required: true
  registry:
    description: 'Container registry'
    required: true
  image-name:
    description: 'Image name (without registry prefix)'
    required: true
  push:
    description: 'Whether to push the image'
    required: false
    default: 'false'
  platforms:
    description: 'Target platforms'
    required: false
    default: 'linux/amd64'
  build-args:
    description: 'Build arguments (multiline)'
    required: false
    default: ''
  registry-username:
    description: 'Registry username'
    required: false
    default: ''
  registry-password:
    description: 'Registry password or token'
    required: false
    default: ''

outputs:
  digest:
    description: 'Image digest'
    value: ${{ steps.build.outputs.digest }}
  tags:
    description: 'Image tags'
    value: ${{ steps.meta.outputs.tags }}
  image-ref:
    description: 'Full image reference with digest'
    value: ${{ inputs.registry }}/${{ inputs.image-name }}@${{ steps.build.outputs.digest }}

runs:
  using: composite
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver: remote
        endpoint: tcp://buildkitd.github-systems.svc.cluster.local:1234

    - name: Log in to Container Registry
      if: inputs.push == 'true'
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.registry-username }}
        password: ${{ inputs.registry-password }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.registry }}/${{ inputs.image-name }}
        tags: |
          # develop → dev-latest, dev-<sha>
          type=raw,value=dev-latest,enable=${{ github.ref == 'refs/heads/develop' }}
          type=raw,value=dev-{{sha}},enable=${{ github.ref == 'refs/heads/develop' }}
          # release/X.Y.Z → X.Y.Z-rc, <sha>
          type=match,pattern=release/(.*),group=1,suffix=-rc
          type=sha,prefix=,format=short
          # hotfix/X.Y.Z → X.Y.Z-hotfix-rc, <sha>
          type=match,pattern=hotfix/(.*),group=1,suffix=-hotfix-rc
          # PR builds → pr-<number>
          type=ref,event=pr,prefix=pr-

    - name: Build and push
      id: build
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        push: ${{ inputs.push }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: ${{ inputs.platforms }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        provenance: true
        sbom: true
        build-args: ${{ inputs.build-args }}
